spring:
  profiles:
    include: aws, github

  h2:
    console:
      enabled: true

  datasource:
    hikari:
      jdbc-url: "jdbc:h2:mem:testdb"
      username: "sa"
      driver-class-name: "org.h2.Driver"

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
